version: "3"

services:

  java_app:
    image: java_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8080
#    depends_on:
#      - mysqldb
    environment:
      JAR_DIR: ./target
      APP_NAME: java_app
      DB_MYSQL_HOST: "mysqldb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "testdb"
      DB_MYSQL_USER: root
      DB_MYSQL_PASS: "123456aA"

#  mysqldb:
#    image: mysql/mysql-server:5.7
#    ports:
#      - 3306:3306
#    container_name: mysql
#    environment:
#      MYSQL_DATABASE: testdb
#      MYSQL_ROOT_PASSWORD: example
#      MYSQL_USER: glopro-rw
#      MYSQL_PASSWORD: Password123