version: '3'
services:
  mysqldb:
    image: mysql/mysql-server:5.7
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: root
    ports:
      - 3306:3306
#    volumes:
#      - my-db:/var/lib/mysql
  hola:
#    image: holaweb
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    environment:
      APP_NAME: java_app
      DB_MYSQL_HOST: mysqldb
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "testdb"
      DB_MYSQL_USER: root
      DB_MYSQL_PASS: 123
    ports:
      - 8081:8081