spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      connection-timeout: 3000
      idleTimeout: 10000
      maxLifetime: 30000


  jackson:
    serialization:
      indent_output: true